name: windows_ai
description: Provides access to WinRT APIs from the Windows.AI namespace using
  FFI.
version: 0.0.2
homepage: https://win32.pub
repository: https://github.com/dart-windows/dartwinrt/tree/main/packages/windows_ai
issue_tracker: https://github.com/dart-windows/dartwinrt/issues?q=is%3Aopen+is%3Aissue+label%3A%22pkg%3A+windows_ai%22
documentation: https://dartwinrt.dev

topics:
  - winrt
  - windows
  - ffi

environment:
  sdk: '^3.0.0'

# Declare that this package only works on Windows.
platforms:
  windows:

dependencies:
  ffi: ^2.0.2
  win32: ^5.0.3
  windows_foundation: ^0.0.7
  windows_graphics: ^0.0.4
  windows_media: ^0.0.3
  windows_storage: ^0.0.2

dev_dependencies:
  test: ^1.24.1
