'area: build & ci':
  - all: ['.github/workflows/*.yml']

'area: docs':
  - all: ['**/*.md']

'area: examples':
  - all: ['packages/*/example/*.{dart,md}']

'area: tests':
  - all: ['packages/*/test/**/*_test.dart']

'pkg: windows_ai':
  - packages/windows_ai/**/*

'pkg: windows_applicationmodel':
  - packages/windows_applicationmodel/**/*

'pkg: windows_data':
  - packages/windows_data/**/*

'pkg: windows_devices':
  - packages/windows_devices/**/*

'pkg: windows_foundation':
  - packages/windows_foundation/**/*

'pkg: windows_gaming':
  - packages/windows_gaming/**/*

'pkg: windows_globalization':
  - packages/windows_globalization/**/*

'pkg: windows_graphics':
  - packages/windows_graphics/**/*

'pkg: windows_management':
  - packages/windows_management/**/*

'pkg: windows_media':
  - packages/windows_media/**/*

'pkg: windows_networking':
  - packages/windows_networking/**/*

'pkg: windows_perception':
  - packages/windows_perception/**/*

'pkg: windows_security':
  - packages/windows_security/**/*

'pkg: windows_services':
  - packages/windows_services/**/*

'pkg: windows_storage':
  - packages/windows_storage/**/*

'pkg: windows_system':
  - packages/windows_system/**/*

'pkg: windows_ui':
  - packages/windows_ui/**/*

'pkg: windows_web':
  - packages/windows_web/**/*

'pkg: winrtgen':
  - packages/winrtgen/**/*
