name: windows_networking
description: Provides access to hostnames and endpoints used by network apps,
  connection profiles that provide connectivity, usage, and data plan
  information for established network connections.
version: 0.0.1
homepage: https://dartwinrt.dev
repository: https://github.com/dart-windows/dartwinrt
issue_tracker: https://github.com/dart-windows/dartwinrt/issues?q=is%3Aopen+is%3Aissue+label%3A%22p%3A+windows_networking%22
publish_to: none # TODO: Remove this

environment:
  sdk: '^2.19.4'

# Declare that this package only works on Windows.
platforms:
  windows:

dependencies:
  ffi: ^2.0.1
  win32:
    git:
      url: https://github.com/timsneath/win32.git
      ref: main
  windows_foundation:
    path: ../windows_foundation
  windows_storage:
    path: ../windows_storage

dev_dependencies:
  test: ^1.22.1
