name: winrtgen
description: Provides functionality to generate Windows Runtime APIs from
  Windows Metadata (WinMD) files.
version: 0.0.1
homepage: https://dartwinrt.dev
repository: https://github.com/halildurmus/dartwinrt
issue_tracker: https://github.com/halildurmus/dartwinrt/issues?q=is%3Aopen+is%3Aissue+label%3A%22p%3A+winrtgen%22
publish_to: none # TODO: Remove this

environment:
  sdk: '^2.19.4'

# Declare that this package only works on Windows.
platforms:
  windows:

dependencies:
  args: ^2.4.0

  # For generating Guid for parameterized types
  crypto: ^3.0.2

  # For formatting Dart code (APIs for performing dart format).
  dart_style: ^2.2.4

  # Foreign Function Interface extension methods
  ffi: ^2.0.1

  html: ^0.15.1
  http: ^0.13.5

  # For calculating the relative file paths
  path: ^1.8.3

  pool: ^1.5.1

  # For working with Windows Metadata (winmd) files
  winmd: ^2.4.8

  win32:
    git:
      url: https://github.com/timsneath/win32.git
      ref: main

dependency_overrides:
  win32:
    git:
      url: https://github.com/timsneath/win32.git
      ref: main

dev_dependencies:
  # Running the test suite.
  test: ^1.22.1
