name: winrtgen
description: Provides functionality to generate WinRT APIs from Windows
  Metadata(WinMD) files.
publish_to: none

environment:
  sdk: '^3.1.0'

platforms:
  windows:

dependencies:
  args: ^2.4.2

  # For generating Guid for parameterized types
  crypto: ^3.0.3

  # For formatting Dart code (APIs for performing dart format)
  dart_style: ^2.3.3

  # Foreign Function Interface extension methods
  ffi: ^2.1.0

  html: ^0.15.4
  http: ^1.1.0

  # For calculating the relative file paths
  path: ^1.8.3

  pool: ^1.5.1

  # Windows metadata for automatically generating API signatures
  winmd: ^4.0.1

  win32: ^5.0.7

dev_dependencies:
  test: ^1.24.6
