name: winrtgen
description: Provides functionality to generate WinRT APIs from Windows
  Metadata(WinMD) files.
publish_to: none

environment:
  sdk: '^3.0.0'

# Declare that this package only works on Windows.
platforms:
  windows:

dependencies:
  args: ^2.4.0

  # For generating Guid for parameterized types
  crypto: ^3.0.2

  # For formatting Dart code (APIs for performing dart format).
  dart_style: ^2.3.0

  # Foreign Function Interface extension methods
  ffi: ^2.1.0

  html: ^0.15.1
  http: ^1.1.0

  # For calculating the relative file paths
  path: ^1.8.3

  pool: ^1.5.1

  # Windows metadata for automatically generating API signatures.
  # The relationship between these two packages is tightly coupled, since this
  # package includes a specific version of the Win32 metadata, so we pin the
  # dependency by version to avoid surprising conflicts.
  winmd: 3.0.1

  win32: ^5.0.7

dev_dependencies:
  # Running the test suite.
  test: ^1.24.1

dependency_overrides:
  winmd:
     git:
      url: https://github.com/dart-windows/winmd.git
      ref: dev
