name: winrtgen
description: Provides functionality to generate WinRT APIs from Windows
  Metadata(WinMD) files.
publish_to: none

environment:
  sdk: '^3.0.0'

# Declare that this package only works on Windows.
platforms:
  windows:

dependencies:
  args: ^2.4.0

  # For generating Guid for parameterized types
  crypto: ^3.0.2

  # For formatting Dart code (APIs for performing dart format).
  dart_style: ^2.3.0

  # Foreign Function Interface extension methods
  ffi: ^2.0.1

  html: ^0.15.1
  http: ^0.13.5

  # For calculating the relative file paths
  path: ^1.8.3

  pool: ^1.5.1

  # For working with Windows Metadata (winmd) files
  winmd: ^2.4.9

  win32:
    git:
      url: https://github.com/timsneath/win32.git
      ref: main

dependency_overrides:
  win32:
    git:
      url: https://github.com/timsneath/win32.git
      ref: main

dev_dependencies:
  # Running the test suite.
  test: ^1.24.1
