name: windows_foundation
description: Enables fundamental Windows Runtime functionality, including
  managing asynchronous operations and accessing property stores.
version: 0.0.1
homepage: https://dartwinrt.dev
repository: https://github.com/halildurmus/dartwinrt
issue_tracker: https://github.com/halildurmus/dartwinrt/issues?q=is%3Aopen+is%3Aissue+label%3A%22p%3A+windows_foundation%22
publish_to: none # TODO: Remove this

environment:
  sdk: '^2.19.4'

# Declare that this package only works on Windows.
platforms:
  windows:

dependencies:
  ffi: ^2.0.1
  win32:
    git:
      url: https://github.com/timsneath/win32.git
      ref: dev
  windows_media:
    path: ../windows_media

dev_dependencies:
  test: ^1.22.1
