name: windows_devices
description: Provides classes for enumerating devices, getting the current
  location or tracking the device's location over time, and getting
  detailed battery information.
version: 0.0.1
homepage: https://dartwinrt.dev
repository: https://github.com/dart-windows/dartwinrt
issue_tracker: https://github.com/dart-windows/dartwinrt/issues?q=is%3Aopen+is%3Aissue+label%3A%22p%3A+windows_devices%22
publish_to: none # TODO: Remove this

topics:
  - winrt
  - windows
  - ffi

environment:
  sdk: '^3.0.0-0'

# Declare that this package only works on Windows.
platforms:
  windows:

dependencies:
  ffi: ^2.0.1
  win32:
    git:
      url: https://github.com/timsneath/win32.git
      ref: main
  windows_applicationmodel:
    path: ../windows_applicationmodel
  windows_foundation:
    path: ../windows_foundation
  windows_storage:
    path: ../windows_storage
  windows_system:
    path: ../windows_system
  windows_ui:
    path: ../windows_ui

dev_dependencies:
  test: ^1.24.1
