name: windows_media
description: >
  Provides classes for creating and working with media such as photos,
  audio recordings and videos.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ffi: ^2.0.1
  win32: ^4.1.0
  windows_foundation:
    path: ../windows_foundation

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
