name: windows_ui
description: Provides an app with access to core system functionality and
  run-time information about its UI.
version: 0.0.1
homepage: https://dartwinrt.dev
repository: https://github.com/halildurmus/dartwinrt
issue_tracker: https://github.com/halildurmus/dartwinrt/issues?q=is%3Aopen+is%3Aissue+label%3A%22p%3A+windows_ui%22
publish_to: none # TODO: Remove this

environment:
  sdk: '>=2.19.2 <4.0.0'

# Declare that this package only works on Windows.
platforms:
  windows:

dependencies:
  ffi: ^2.0.1
  win32:
    git:
      url: https://github.com/timsneath/win32.git
      ref: dev
  windows_data:
    path: ../windows_data
  windows_foundation:
    path: ../windows_foundation
  windows_system:
    path: ../windows_system

dev_dependencies:
  test: ^1.22.1
