name: windows_ui
description: >
  Provides an app with access to core system functionality and run-time
  information about its UI.
version: 0.0.1
homepage: https://dartwinrt.pub
repository: https://github.com/halildurmus/dartwinrt
issue_tracker: https://github.com/halildurmus/dartwinrt/issues?q=is%3Aopen+is%3Aissue+label%3A%22p%3A+windows_ui%22
publish_to: none # TODO: Remove this

environment:
  # Change upper constraint to <4.0.0 when this PR is deployed to pub.dev:
  #   https://github.com/dart-lang/pub-dev/pull/6269
  sdk: '>=2.17.0 <3.0.0'

# Declare that this package only works on Windows.
platforms:
  windows:

dependencies:
  ffi: ^2.0.1
  win32: ^4.1.0
  windows_foundation:
    path: ../windows_foundation

dev_dependencies:
  test: ^1.22.1
