name: Upload code coverage reports

on:
  pull_request:
    paths:
      - 'packages/windows_foundation/**'
      - 'packages/winrtgen/**'
  push:
    branches:
      - main
    paths:
      - 'packages/windows_foundation/**'
      - 'packages/winrtgen/**'

jobs:
  windows_foundation:
    defaults:
      run:
        working-directory: packages/windows_foundation

    runs-on: windows-2022

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3

      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: main

      - name: 📦 Install Dependencies
        run: dart pub get

      - name: Install coverage
        run: dart pub global activate coverage

      - name: 📊 Generate Code Coverage
        run: dart pub global run coverage:test_with_coverage

      - name: Upload Code Coverage Reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: coverage/lcov.info

  winrtgen:
    defaults:
      run:
        working-directory: packages/winrtgen

    runs-on: windows-2022

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3

      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: main

      - name: 📦 Install Dependencies
        run: dart pub get

      - name: Install coverage
        run: dart pub global activate coverage

      - name: 📊 Generate Code Coverage
        run: dart pub global run coverage:test_with_coverage

      - name: Upload Code Coverage Reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: coverage/lcov.info
